@startuml
skinparam Style strictuml


[*] --> Sesion_iniciada: Iniciar sesion
Sesion_iniciada --> Sesion_iniciada: Modificar informacion del perfil
Sesion_iniciada --> Administrando_Usuarios: Administrar usuarios
Administrando_Usuarios --> Administrando_Usuarios: Agregar usuario
Administrando_Usuarios --> Administrando_Usuarios: Eliminar usuario
Administrando_Usuarios --> Sesion_iniciada

Sesion_iniciada --> Viendo_Examenes: Ver lista de examenes
Viendo_Examenes --> Viendo_Examenes: Modificar examen
Viendo_Examenes --> Sesion_iniciada
Sesion_iniciada --> [*]: Cerrar sesion

@enduml