@startuml
skinparam Style strictuml

state choice1 <<choice>>
state choice2 <<choice>>
state choice3 <<choice>>
[*] --> Sesion_iniciada: Iniciar sesion
Sesion_iniciada --> Buscado: Buscar contenido en la documnetacion
Buscado --> Documentacion_Vista: ver documentacion
Documentacion_Vista-->choice1: Desea buscar otro tema en la documentacion?
choice1 --> Buscado: Si
choice1 --> Sesion_iniciada: No

Sesion_iniciada --> Cursos_Vistos: Ver lista de cursos
Cursos_Vistos --> Curso_Seleccionado: Seleccionar curso
Curso_Seleccionado --> Examenes_Vistos: Ver lista de examenes
Examenes_Vistos --> Examen_Seleccionado: Seleccioanr examen
Examen_Seleccionado --> Preguntas_respondidas: Responder preguntas 
Preguntas_respondidas --> choice2: Desea ver las respuestas correctas?
choice2 --> RespuestasCorrectas_Vistas: Si
RespuestasCorrectas_Vistas --> Examen_Enviado: Enviar examen
choice2 --> Examen_Enviado: No
Examen_Enviado --> Resultado_Visto: Ver resultado
Resultado_Visto --> choice3: Desea ver otro curso?
choice3 --> Sesion_iniciada: Si
choice3 --> Certificado_Visto: Ver certificado
Certificado_Visto --> Certificado_Descargado: Descargar certificado
Certificado_Descargado --> [*]: Cerrar sesion


@enduml
