@startuml
left to right direction

actor Admin as A
actor Usuario as U1

rectangle "Sistema de Cursos y Certificados" {
  
  A --> (Agregar Usuario)
  A --> (Modificar Usuario)
  A --> (Eliminar Usuario)
  A --> (Ver Detalles de Usuario)
  U1 --> (Ver Documentación)
  U1 --> (Buscar en la Base de Conocimientos)
  U1 --> (Ver Lista de Cursos)
  U1 --> (Seleccionar Curso)
  U1 --> (Ver Lista de Exámenes)
  U1 --> (Seleccionar Examen)
  U1 --> (Responder Preguntas)
  U1 --> (Enviar Examen)
  U1 --> (Ver Resultados)
  U1 --> (Ver Respuestas Correctas)
  U1 --> (Ver Certificado)
  U1 --> (Descargar Certificado)
  A --> (Ver Lista de Exámenes)
  A --> (Modificar Examen)
  U1 --> (Cerrar Sesión)
  
  (Responder Preguntas) ..> (Ver Respuestas Correctas) : include
  (Enviar Examen) ..> (Ver Resultados) : include
  (Ver Lista de Exámenes) ..> (Modificar Examen) : extend
}

@enduml
