@startuml

skinparam Style strictuml

[*] --> Credenciales_Verificadas: Verifiacion de credenciales del alumno
Credenciales_Verificadas--> Credenciales_Verificadas: Editar informacion del alumno
Credenciales_Verificadas --> Examen_Seleccionado: Seleccionar un tipo de examen
Examen_Seleccionado--> Presentando_Examen: Presentar examen
Presentando_Examen --> Presentando_Examen: Reponder pregunta
Presentando_Examen --> Examen_Finalizado: Finalizar examen
Examen_Finalizado --> Viendo_Resultado: Ver resultado
Viendo_Resultado --> Credenciales_Verificadas
Viendo_Resultado --> [*]: Recibir certificado

@enduml