@startuml
left to right direction
hide footbox
hide link
Actor Student
boundary AvailableExamsView
boundary ExamView
boundary EndExamView
entity Exam
entity Puntuation
entity Question
control StartExamController
control EndExamController
control PrensentExamContoller
control AnwswerQuestionController

Student  -- AvailableExamsView
AvailableExamsView -- ExamView
StartExamController -- Exam
ExamView -- EndExamView
Exam -- Question
Exam -- Puntuation
Question -- Puntuation
EndExamView -- PrensentExamContoller
EndExamController -- Puntuation
ExamView -- PrensentExamContoller
PrensentExamContoller -- StartExamController
PrensentExamContoller -- EndExamController
PrensentExamContoller -- AnwswerQuestionController
AnwswerQuestionController -- Question

@enduml