@startuml DiagramaDeEstadosDeUseCasesUsuario
skinparam Style strictuml


[*] --> Sesion_iniciada: Iniciar sesion
Sesion_iniciada --> Sesion_iniciada: Modificar inofrmacion del perfil


Sesion_iniciada -->  Examenes_Vistos: Ver lista de examenes
Examenes_Vistos --> Resolviendo_Examen: Resolver examen
Resolviendo_Examen --> Resolviendo_Examen: Responder preguntas 
Resolviendo_Examen --> Examen_Finalizado: Finalizar examen
Examen_Finalizado --> Resultado_Visto: Ver resultado
Resultado_Visto --> Viendo_Certificado: Ver certificado
Viendo_Certificado -->  Sesion_iniciada
Sesion_iniciada --> [*]: Cerrar sesion


@enduml
