@startuml
left to right direction
hide footbox
hide link
Actor Alumno
boundary ExamenesDisponibles
boundary VerExamen
boundary FinalizarExamen
entity Instruccion
entity Examen
entity Puntuacion
entity Pregunta
control InicioExamen
control FinExamen

Alumno  -- ExamenesDisponibles
ExamenesDisponibles -- VerExamen
VerExamen -- InicioExamen
InicioExamen -- Instruccion
InicioExamen -- Examen
Instruccion -- Examen
Examen -- Pregunta
Examen -- Puntuacion
Pregunta -- Puntuacion
VerExamen -- FinalizarExamen
FinalizarExamen -- FinExamen
FinExamen -- Puntuacion

@enduml