@startuml
left to right direction
hide footbox
hide link
Actor Alumno
boundary ExamenesDisponibles

boundary VerExamen
entity Instruccion
entity Examen
entity Puntuacion
entity Pregunta
control InicioExamen

Alumno  -- ExamenesDisponibles
ExamenesDisponibles -- VerExamen
VerExamen -- InicioExamen
InicioExamen -- Instruccion
InicioExamen -- Examen
Instruccion -- Examen
Examen -- Pregunta
Examen -- Puntuacion
Pregunta -- Puntuacion
@enduml