@startuml DiagramaDeEstadosDeUseCasesAdmin
skinparam Style strictuml


[*] --> Sesion_iniciada: Iniciar sesion
Sesion_iniciada --> Sesion_iniciada: Modificar informacion del perfil
Sesion_iniciada --> Agregando_Usuarios: Agregar usuarios
Agregando_Usuarios --> Sesion_iniciada

Sesion_iniciada --> Viendo_Examenes: Ver lista de examenes
Viendo_Examenes --> Viendo_Examenes: Agregar examen
Viendo_Examenes --> Sesion_iniciada
Sesion_iniciada --> [*]: Cerrar sesion

@enduml