@startuml Class
left to right direction
skinparam Nodesep 40
skinparam boxsize 100 50
skinparam noteBackgroundColor transparent
skinparam noteBorderColor transparent
hide methods

class Persona{
  # nombre: String
  # apellido: String
}

class Estudiante {

}

class Perfil{
}

abstract Administrador {
}

class Examen {
  # nombre: String
  - instrucciones: String
  - tiempo: uint
}

class Pregunta {
  - texto: String
  - respuestaCorrecta: String
  - justificacion: String
  - resultadoRespuesta: bool
}

class Certificado {
  - nombreCertificado: String
  - fecha: Date
  - nombreProfesores: String
  - nombreEstudiante: String
  - ExamenesRealizados: String
}

class Curso{
  - nombreCurso: String
  - profesores: String
}

class Dominio{
  dominio string 
}

Administrador --|> Persona
Estudiante --|> Persona
Curso "1..*" o-- "0..*" Estudiante
Curso "1" *-- "1" Examen
Persona "1" -- "1" Perfil : tiene un >
Administrador "1" -- "1..*" Examen : crea un >
Examen "1" *-- "1..*" Pregunta : tiene
Profesor "1..*" -- "0..*" Estudiante : registra a > 
Pregunta "1" *-- Dominio: Posee
(Curso,Estudiante) . Certificado

@enduml