@startuml DiagramaEstadoAdmin

[*] --> Credenciales_Validadas: Validacion de credenciales del adminstrador
Credenciales_Validadas --> Administrando_Alumnos : Administrar alumnos
Administrando_Alumnos --> Administrando_Alumnos: Agregar Alumno
Administrando_Alumnos --> Administrando_Alumnos: Eliminar Alumno
Administrando_Alumnos --> Credenciales_Validadas
Credenciales_Validadas --> Administrando_Examenes : Administrar examenes
Administrando_Examenes --> Administrando_Examenes: Modificar examen
Administrando_Examenes --> Credenciales_Validadas
Credenciales_Validadas --> [*]: Finalizar

@enduml