@startuml DiagramaSecuencia

actor Student
boundary RequestCertificateView
control RequestCertificateController
entity User
entity Certificate
entity Course


activate Student
Student -> RequestCertificateView: viewCertificate()
activate RequestCertificateView
RequestCertificateView -> RequestCertificateController: request(user)
activate RequestCertificateController
RequestCertificateController -> User: getUserData(user)
activate User
User -> Course: getCourseData(courseID)
activate Course
Course --> User: courseData
deactivate Course
User --> RequestCertificateController: userData
deactivate User
RequestCertificateController -> Certificate: new Certificate()
activate Certificate
RequestCertificateController -> Certificate: writeData(userData)
Certificate --> RequestCertificateController: certificate
deactivate Certificate
RequestCertificateController --> RequestCertificateView: certificate
deactivate RequestCertificateController
RequestCertificateView --> RequestCertificateView: showCertificate(certificate)


@enduml