@startuml DiagramaSecuencia

actor Student
entity RequestCertificateView
entity RequestCertificate
entity User
entity Certificate
entity Course


activate Student
Student -> RequestCertificateView: view_certificate()
activate RequestCertificateView
RequestCertificateView -> RequestCertificate: request(user)
activate RequestCertificate
RequestCertificate -> User: set_certificate_data(user)
activate User
User -> User: get_data()
User --> RequestCertificate: user_data
User -> Course: get_data()
activate Course
Course -> Course: get_data()
Course --> User: course_data
deactivate Course
User --> RequestCertificate: course_data
deactivate User
RequestCertificate -> Certificate: createCertificate()
activate Certificate
Certificate -> Certificate: write_data(user_data, course_data)
Certificate --> RequestCertificate: certificate
deactivate Certificate
RequestCertificate --> RequestCertificateView: certificate
deactivate RequestCertificate
RequestCertificateView --> Student: show_certificate(certificate)
deactivate RequestCertificateView

@enduml