@startuml DiagramaSecuencia

actor Student
boundary RequestCertificateView
control RequestCertificateController
entity User
entity Certificate
entity Course


activate Student
Student -> RequestCertificateView: view_certificate()
activate RequestCertificateView
RequestCertificateView -> RequestCertificateController: request(user)
activate RequestCertificateController
RequestCertificateController -> User: get_user_data(user)
activate User
User -> Course: get_course_data(courseID)
activate Course
Course --> User: course_data
deactivate Course
User --> RequestCertificateController: user_data
deactivate User
RequestCertificateController -> Certificate: new Certificate()
activate Certificate
RequestCertificateController -> Certificate: write_data(user_data)
Certificate --> RequestCertificateController: certificate
deactivate Certificate
RequestCertificateController --> RequestCertificateView: certificate
deactivate RequestCertificateController
RequestCertificateView --> RequestCertificateView: show_certificate(certificate)


@enduml