@startuml DiagramaClasesDeAnalisisSolicitarCertificado

:Student: as o1


boundary RequestCertificateView

control "RequestCertificate" as o2


entity "User" as o4
entity "Course" as o5
entity "Certificate" as o6

o1 --> RequestCertificateView

RequestCertificateView --> o2
o2 --> o4
o2 --> o5

o4 -- o5
o2 --> o6 



@enduml