@startuml DiagramaDeClasesGenerales

class HomeView {}

class Result
{ 
    -score 
    -setScore() 
}

class User
{ 
    -name 
    -lastName 
    -email 
    +getName() 
    +getLastName() 
    +getEmail() 
}

class InstructionsView{

}

class Exam
{ 
    -question 
    -answer 
}

class Question 
{ 
    -statement 
    -answer 
    +setAnswer() 
}

class AnswerQuestionController{}

class TakeExamController{}

class ExamView
{ 
    +showExam(TakeExamController) 
+back() 
    +next() 
    +showQuestion(AnswerQuestionController) 
}


class Certificate
{
    -nameStudent
    -nameProfessor
    -nameCourse
    -result
    +write()
}

class RequestCertificate{}

class RequestCertificateView
{ 
    -showCertificate(RequestCertificateView) 
}
class Answer{}

class MenuBar{
+house()
+frequentQ()
+help()
+search()
}

HomeView *-- RequestCertificateView
InstructionsView *-- ExamView 
RequestCertificateView  *--InstructionsView
RequestCertificateView-->RequestCertificate
ExamView --> TakeExamController
TakeExamController--> AnswerQuestionController
RequestCertificate-->Certificate
Certificate --> User

TakeExamController--> Exam
TakeExamController--> Result
AnswerQuestionController--> Question
Exam --> Question
Exam --> Result
User --> Result
User --> Answer
Question --> Answer
ExamView *-- MenuBar
RequestCertificateView *-- MenuBar
InstructionsView *-- MenuBar

 @enduml