@startuml DiagramaColaboracionPresentarExamen
skinparam EntityBackgroundColor white
skinparam BoundaryBackgroundColor white
skinparam ControlBackgroundColor white
skinparam ActorBackgroundColor white
skinparam noteBackgroundColor transparent
skinparam noteBorderColor transparent
hide members
top to bottom direction

actor ":Student" as estudiante

control ":TakeExamController" as presentar
control ":AnswerQuestionController" as Responder
entity ":Exam" as Examen
boundary ":ExamView" as Ver
Entity ":Results" as Resultado

estudiante -- Ver
Ver -- presentar
presentar -- Examen
presentar -- Responder
Responder -- Examen
Resultado --  presentar



@enduml