@startuml DiagramaColaboracionPresentarExamen
skinparam EntityBackgroundColor white
skinparam BoundaryBackgroundColor white
skinparam ControlBackgroundColor white
skinparam ActorBackgroundColor white
skinparam noteBackgroundColor transparent
skinparam noteBorderColor transparent
hide members
top to bottom direction

actor ":Student" as estudiante

control ":TakeExamController" as presentar
entity ":Exam" as Examen
Entity ":Results" as Resultado
boundary ":ExamView" as Ver

estudiante --> Ver
note on link
    0: AcceptInstructions()
    1: TakeExam()
    4: GetAnswer()
    8: Back()
end note

Ver -- presentar
note on link
    2: GetExam()
    5: SetResult()
end note

presentar <-- presentar
note on link
    6: Back()
end note

presentar -- Examen
note on link
    3: getData()
end note

presentar -- Resultado
note on link
    7: setResult()
end note